services:
  db:
    image: docker.io/library/postgres:17-alpine
    environment:
      POSTGRES_USER: sgp_user
      POSTGRES_PASSWORD: sgp_password
      POSTGRES_DB: sgp
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgp_user -d sgp"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: Containerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://sgp_user:sgp_password@db:5432/sgp
      JWT_SECRET: sgp_super_secret_2026
      JWT_EXPIRES_IN: 30m
      PORT: "3000"
      NODE_ENV: development
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: Containerfile.nginx
    depends_on:
      - backend
    ports:
      - "8080:80"
volumes:
  pgdata:
