apiVersion: v1
kind: Pod
metadata:
  name: sgp-pod
  labels:
    app: sgp
spec:
  containers:
    # 1. Base de datos PostgreSQL
    - name: db
      image: docker.io/library/postgres:17-alpine
      env:
        - name: POSTGRES_USER
          value: sgp_user
        - name: POSTGRES_PASSWORD
          value: sgp_password
        - name: POSTGRES_DB
          value: sgp
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d/init.sql:Z
          readOnly: true

    # 2. Backend Node.js
    - name: backend
      image: localhost/sgp-backend:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_URL
          value: postgresql://sgp_user:sgp_password@127.0.0.1:5432/sgp
        - name: JWT_SECRET
          value: sgp_super_secret_2026
        - name: JWT_EXPIRES_IN
          value: 30m
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: development

    # 3. Frontend Nginx
    - name: frontend
      image: localhost/sgp-frontend:latest
      imagePullPolicy: IfNotPresent
      ports:
        # Exponemos el puerto de Nginx hacia la máquina host
        - containerPort: 80
          hostPort: 8080

  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: pgdata-claim
    - name: db-init
      hostPath:
        path: ./db/init.sql
        type: File
