apiVersion: v1
kind: Pod
metadata:
  name: sgp-app
  labels:
    app: sgp
spec:
  hostname: sgp-app
  containers:
    - name: backend
      image: localhost/sgp-backend:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_URL
          value: postgresql://${DB_USER}:${DB_PASSWORD}@sgp-db:5432/${DB_NAME}
        - name: JWT_SECRET
          value: ${JWT_SECRET}
        - name: JWT_EXPIRES_IN
          value: ${JWT_EXPIRES_IN}
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: ${NODE_ENV}
        - name: BREVO_API_KEY
          value: ${BREVO_API_KEY}
        - name: BREVO_SENDER_EMAIL
          value: ${BREVO_SENDER_EMAIL}
        - name: BREVO_SENDER_NAME
          value: ${BREVO_SENDER_NAME}

    - name: frontend
      image: localhost/sgp-frontend:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: ${FRONTEND_PORT}
