apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sgp-pgdata
  labels:
    app: sgp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: sgp-db
  labels:
    app: sgp
spec:
  hostname: sgp-db
  containers:
    - name: db
      image: docker.io/library/postgres:17-alpine
      env:
        - name: POSTGRES_USER
          value: sgp_user
        - name: POSTGRES_PASSWORD
          value: sgp_password
        - name: POSTGRES_DB
          value: sgp
      volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d/init.sql:Z
          readOnly: true
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: sgp-pgdata
    - name: db-init
      hostPath:
        path: ./db/init.sql
        type: File
